title: Rocio Soledad Radulescu
logo: "/images/logo_git.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <p style="color:gray"><b>Big data - Data engineer</b></p> 
  <a href="mailto:rsradulescu@gmail.com?Subject=Enlace%20portfolio">Email</a>
  <br><br>
  <a href="https://www.linkedin.com/in/rsradulescu/">LinkedIn</a> 
theme: jekyll-theme-slate
