title: Cecil Fabrizio # your name (or website title) here
logo: "/images/PXL_20230119_212326867.PORTRAIT.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bio
  <br><br>
  Recent graduate of the University of Colorado, Boulder. Recieving a BA in Mathematics and an MS in Business Analytics. 
  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
