title: Sam Alqarzi # your name (or website title) here
logo: "/images/IMG_0395 2.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description
  <br><br>
  Second description
  <br><br>
  <a href="https://www.linkedin.com/in/salem-alqarzi-566219133/">View My LinkedIn Profile</a>
  <a href="https://github.com/SamAlqarzi/">View My Github Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
