title: <p align="center"> Andrew Schell</p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/andrewschell/">LinkedIn</a> |
  <a href="https://github.com/datatalking">GitHub</a>
  </p>
  
  <p align="justify">
  </d></d>I am pursing an MIXx Micro Masters degree in Statistics and Data Science from Massachusetts Institute of Technology online via Coursera.
  <br><br>
  I'm a Full Stack Product Data Analyst, my research and study of over 400 github repos of
  engineering interests are mainly in the areas of data cleaning, NLP chatbot agents, artificial intelligence, and algorithms that identify patterns for business or social value in
  user-friendly software
  engineering..
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
# TODO update google analytics ID
google_analytics: G-FVCXTYHXBV # Google Analytics tracking ID
