title: Matthew Lim # your name (or website title) here
logo: "/images/mlim.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/matthewklim/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-WRVE5934HY # your Google Analytics tracking ID here
