title: Sarah Carpe # your name (or website title) here
logo: "/images/PicsArt_03-20-11.46.38.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  2+ years expereince with GIS platforms: ArcGIS, QGIS, R.
  <br><br>
  3+ years experience with lab management and molecular biology techniques.
  <br><br>
  GIS Research Assistant for USDA Forest Service, Student Researcher at UMBC, Environmental Science B.S. '2020
  <br><br>
  <a href="https://www.linkedin.com/in/sarah-carpe-10a128180">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.instagram.com/allthingswild.photos/">View My Instagram Profile</a>
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
