title: Madilyn Moeller # your name (or website title) here
logo: "/images/mortarboard-moellem3.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Writer, Editor, Humanities Scholar
  <br>
  Miami University(OH) 2020. Psychology, Neuroscience, & Professional Writing. <br />
  <a href="/about/">Resume</a> <br />
  <a href="https://www.linkedin.com/in/madilyn-moeller/">View my LinkedIn</a>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here 
