title: John Wong # your name (or website title) here
logo: "/images/IMG_2937_circle_small.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I've worked with government agencies, legislators, and developers on macroeconomics, regulatory policy, and foreign policy. As a data scientist, I use R and Python for machine learning, web scraping, forecasting, and data visualization. 
  <br>
  <br>
  I am currently an Applied Research Fellow at the Mercatus Center.
  <br>
  <br>
  <a href="https://www.linkedin.com/in/johnthwong/">View My LinkedIn</a> 
  <br>
  <br>
  <a href="https://economics.gmu.edu/people/twong7">View My Department Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# google_analytics: G-CXRL3XP9BW # your Google Analytics tracking ID here
