title: Salma Abdelhamid # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, and welcome to my profile! 
  <br><br>
  I am a Master of Science in Business Analytics
  candidate at Simon Business School. 
  My background is in Finance and 
  I was a Financial Analyst at UnitedHealthcare.  
  <br><br>
  <a href="https://www.linkedin.com/in/salma-abdelhamid/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
