title: Zack Koppert # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer 
  <br><br>
  GitHub, DevOps Team
  <br><br>
  Previously Tektronix, Open Source Team
  <br><br>
  <a href="https://www.linkedin.com/in/zack-koppert/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
