title: William Denning # your name (or website title) here
logo: "/images/avatarCircle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Developer-in-training.
  <br><br>
  NYC
  <br><br>
  <a href="https://www.linkedin.com/in/williamadenning/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
