title: YANKEE MAJUMDER # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior System Engineer 
  <br><br>
  Equipped with a deep understanding of IAM technologies, I've architected robust workspace infrastructures, empowering businesses to embrace remote work, Modern workplace and infrastructure Management. ğŸŒ Whether it's integrating identity management systems or fine-tuning access controls, I thrive on crafting tailored solutions that align with business objectives and regulatory requirements. ğŸš€ My commitment to staying at the forefront of industry trends drives me to continuously enhance my skills, ensuring that I can leverage the latest advancements to drive value for my team and organization
  <br><br>
  <a href="https://www.linkedin.com/in/yankee-majumder-6870ba134/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

